### ISSUE TITLE
Autocomplete does not work with Version 31.6.0 on Macbook Air Yosemite 10.10.3

### ISSUE THREAD

**Issue by romsson** [nostalgy/nostalgy#12]
However, the Dev versionof the extension (0.2.33) works with a manual install

**Comment by caugner** [comment]
Closing this issue for now, as more information is needed to investigate.

If you are still affected by this issue, please provide the following information:

1. What steps will reproduce the problem?
2. What is the expected output? What do you see instead?
3. What version of the product are you using? On what operating system?
