### ISSUE TITLE
[SOLVED?] Newest dev build (0.2.33+) works on TB31.7.0

### ISSUE THREAD

**Issue by arnotixe** [nostalgy/nostalgy#14]
Hi Alain/all

I just upgraded here (to TB31.7.0) and found nostalgy was still working moving messages around and also to the default suggested location, only thing is, the popup didn't show nor appear/update while typing.

Updated to today's "current build", which turned out to be 0.2.23, and it works again :dancers: 

¡Nostalgy rocks and should be included by default in TB!

**Comment by mjg** [comment]
Could you clarify the version numbers please (there seem to be typos)? I.e., which one gave you which problem, and which one solved it?

**Comment by caugner** [comment]
Closing, as the reporter already mentioned that it works again.

Also, this sounds like #10 and should have been fixed in 0.2.24.
