### ISSUE TITLE
Incomplete list of matches

### ISSUE THREAD

**Issue by mjg** [nostalgy/nostalgy#16]
TB 31.7.0 (Fedora 21) with Nostalgy 0.2.33

Starting after a recent TB update (can't say which one, sorry), the list of save destination matches that Nostalgy returns is too small. E.g.:

Folder "GMail/EinsundEins" is matched by the search terms "su" and "ins" but not by "sun" nor "Eins".

This happens for some folders, but not all. In fact, it seems as if it (successful partial match, unsuccessfull full match or longer partial match) happened for all "recent" folders (those offered without match) but not for others. I can't be sure because I have too many folders, and there is one exception, which is a folder "Posteingang", the inbox from one account, which is "recent" but also matched; I have many more folders with that name, of course.

**Comment by caugner** [comment]
This sounds like #61 and I'm closing this in favor of this more recent issue.

Even though the description differ a bit, there's a chance that fixing #61 also fixes this.
