### ISSUE TITLE
Problems with keyword shortcuts

### ISSUE THREAD

**Issue by rhorbas** [nostalgy/nostalgy#17]
In TB 38.0.1 (Win7) Nostalgy seems to collide with the
keyword shortcuts: Pressing the keys 0-9 to assign a keyword to a mail
doesn't work for me anymore. Only if I disable Nostalgy, I can use the
function.

**Comment by hawk-ip** [comment]
I don't have this problem, it works fine, suggest this can be closed.

**Comment by caugner** [comment]
Closing this issue for now, as it's 4,5 years old and more information would be needed to properly investigate the issue:

* What keyboard layout is used?
* What keys are set in the Nostalgy preferences?
