### ISSUE TITLE
Enhancement request: Folder tab view is reset to top instead of centering on chosen folder

### ISSUE THREAD

**Issue by SKelem** [nostalgy/nostalgy#21]
When I use Nostalgy to select a folder, the folder tab (on the left side of the Thunderbird window) scrolls to the top (1st account). I have to scroll down to find the selected folder. This behavior is annoying because I have to scroll to find the selected folder, resulting in a loss of time, focus & concentration.

It would be better if the folder tab put the selected folder in view (top or middle of the tab). The selected folder is already highlighted (a good thing).

It would be less good, but better than the reset, if the folder view remained unchanged.

**Comment by hi5** [comment]
If I type 'g' again the folder tab will focus on the correct selected folder. You can press 'esc' to cancel the folder search but the folder tab for me (Windows 7, 32 bit) has the correct folder in view.

**Comment by SKelem** [comment]
That's useful, but it would be better if it did it the first time
      I hit "g", which is when I searched for the folder. Hitting "g" a
      2nd time, which starts another search, is not intuitive.
    Steve
    
    
    hi5 wrote on 02/29/2016 03:16 PM:
    
    
      If I type 'g' again the folder tab will focus on the correct
        selected folder. You can press 'esc' to cancel the folder search
        but the folder tab for me (Windows 7, 32 bit) has the correct
        folder in view.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by hi5** [comment]
Unfortunately this work around no longer works :sob:

**Comment by hi5** [comment]
Just to note: if you double click on a message it will of course open in a new tab, after you close this tab the folder tab now has the correct focus on the selected folder.

**Comment by caugner** [comment]
Closing this issue as a duplicate in favor of #19.

Please note [the workaround](https://github.com/nostalgy/nostalgy/issues/19#issuecomment-589289209) mentioned there (and verified in 0.3):
