### ISSUE TITLE
Feature Request: Send and directly move a copy to a specific folder

### ISSUE THREAD

**Issue by solonair** [nostalgy/nostalgy#30]
It would be great if nostalgy could save and move a copy of the sent message directly after sending.

**Comment by alainfrisch** [comment]
Thunderbird allows you to keep a copy of the sent messages in a folder of your choice.  How would this be different?

**Comment by solonair** [comment]
I would like to keep an extra copy of my sent mails in the same folder where I move the received mails. Right now, I sent myself an BCC and store it later with nostalgy. However, I would rather save an extra copy right after sending to be still in context.

There is an extra add on for this: https://addons.mozilla.org/de/thunderbird/addon/copy-sent-to-current/ but it is rather cumbersome and it does not support the keyboard like Nostalgy which I prefer.

**Comment by caugner** [comment]
If I'm not mistaken:

* So far Nostalgy only works on selected messages in the message list.
* The reporter would like to apply move/copy actions on sent messages as soon as they are saved.

**If you would like this behaviour**, please try if this cannot already be achieved using TB Filters ( `Apply filter when: [x] After Sending`) and share your feedback.

Closing this for now.
