### ISSUE TITLE
Problems with keys non-ascii letters

### ISSUE THREAD

**Issue by torinthiel** [nostalgy/nostalgy#31]
When I define a keyboard shortcut to move message to a specific folder, and that folder contains non-ASCII characters (Polish diacritics to be specific), the command does not work - pressing the key has no effect.

When I close and re-open the preferences page sometimes, depending on the character in question, the shortcut is displayed properly (probably when the folder name contains 'ó'), more often the diacritic gets replaced with something else (I recall 'B' and '&' being used).

**Comment by caugner** [comment]
Closing this in favor of #4. Fixing that issue should also fix this one.
