### ISSUE TITLE
compatibility with last version of thunderbird.

### ISSUE THREAD

**Issue by cucupio** [nostalgy/nostalgy#37]
Will nostalgy contiue to be compatible with last version?

**Comment by alainfrisch** [comment]
It seems to work ok with the latest version.  I've bumbed the maximum supported version accordingly.  Can you confirm it works for you as well?

**Comment by pcause** [comment]
as issue #39 points out it isn't working with the latest beta.  seemed to work fine with 58.x versions but something changed in 59b1 and doesn't work with b2 either

**Comment by karakatsanism** [comment]
hi, I am using thunderbird 58 b3 and nostalgy 2.35 and I cannot save/copy/save and go message to folder (imap). Go to folder and show/hide folder pane works fine though.

**Comment by JoelAzaria** [comment]
@cucupio there is a TB 60 compatibility thread (#46 I think) that has this working and deals with a few 'residual' non-working features.
Recommend you close this issue (as it's stale by now) and, if you need, follow that one.

**Comment by caugner** [comment]
Closing this issue, as Nostalgy 0.3 is currently compatible with the latest TB version 68.
