### ISSUE TITLE
shortcut to go to last unread message ?

### ISSUE THREAD

**Issue by Ulrar** [nostalgy/nostalgy#47]
Hi,

Just installed it, and while I like the G key to go to the folder, I find that after that pressing either key will take me all the way up to the first message. I have years of messages in each folder, and scrolling down with page down is just unthinkable.
Is there some key I'm missing to scroll down instantly ? Right now I have to use the mouse to do that, which defeats the purpose.
Thanks

**Comment by r2evans** [comment]
Wouldn't <kbd>End</kbd> be good enough? It may over-shoot the last *unread* depending on what you've done previously, but it will almost certainly get you much closer.

**Comment by caugner** [comment]
I agree with @r2evans that <kbd>End</kbd> should solve this.

Another solution would be to `View -> Sort by -> (x) Date + (x) Descending`, which shows the latest message first.

Closing this issue, as it's out of the scope of Nostalgy.
