### ISSUE TITLE
Nostalgy stripping tags on move (save)

### ISSUE THREAD

**Issue by JoelAzaria** [nostalgy/nostalgy#57]
So afaik this is new, probably as of TB60 but I can't be sure.   Sometimes when moving (saving) an email w/ nostalgy it ends up in the target folder but with all the tags stripped off.

I'm not sure exactly what causes it and it doesn't happen every time but I seem to be able to replicate at least some times.

What I *think* happens is the first time I move a message (or bunch) after I've create a folder using nostalgy it strips the tags.  I have not observed this with drag and drop moves (which I never do, only for testing this did I try a few)

Here's my exact process, could anyone else please confirm?
Give your OS and tbird versions too please  I'm on Win 10 64 and TB 60.2.1 (32b)

1. Search a term (ctrl+k)  and press enter.  Search results open in another tab.
1. From the search list choose "open email as list"   List opens in yet another tab

1. Select one or select all messages  (the messages should have tags on them)
1. Hit 's' for nostalgy save
1. Type a folder location that exists and then create a new subfolder.  eg. if I have a folder called "Mozilla Tickets" somewhere, I type "mozilla", I select "mozilla tickets" to grab the full path and I add "/12341234" to create the new ticket number folder.
1.  I get an error from Nostalgy that the folder doesn't exist and asking if I want to create it it.  Click OK.
1. The folder is created but the message isn't moved.  Typs 's' again for nostalgy move and type the folder you just created, eg '12341234' and this time the messages move.
1. go to target folder.  whatever tags were on the messages are stripped.

Subsequent moves to the same or other existing folders do not seem to strip the tags.  Except for creating the folder the rest of the procedure is same as above but tags not lost.

Edit ----
so just a follow up, this definitely does not happen EVERY time.  I just created a folder and moved a tagged message to the new folder and the tag persisted.  Very strange but also disconcerting..

**Comment by JoelAzaria** [comment]
More data points - 
Same procedure as above, hit save, created a new folder, etc.
Then I did a 'b' (bounce, ie save and follow) to the dest folder.  I moved 6 messages. 
All 6 had a common tag and one (the first/oldest chronologically) had 2 add'l.

After the move only the first message was stripped of all 3 tags.  The other 5 retained the one tag.

Of the 3 tags that were stripped, two of them are within the first 9 tags (meaning they have number key shortcuts) just in case there is any significance.  Just documenting as much as I can think of.

**Comment by caugner** [comment]
This sounds like a TB bug, because Nostalgy only uses an API to move a message (cf. #54) and TB should never discard the tags, even if the target folder doesn't exist or similar.

I do remember that TB discarded tags for me at times in the past for all messages in a folder, because that folder got corrupted apparently and had be repaired.

@JoelAzaria Do you still experience this in 0.3 with TB 68? I know that the TB folks have been working hard on fixing weird bugs like this recently.

**Comment by JoelAzaria** [comment]
Not sure.  Have recently made changes including upgrading machines and some TB problems like crashing seem to have cleared up.  Possibly was a bad NIC or SSD in the old machine, not 100% sure, that may have contributed to folders corrupting a bit too often

Also my email flows are breaking down due to numbers of extensions not working for me.  Seriously considering going back to TB 60 or just bailing on tbird altogether :(

For now I think you can consider this closed unless/until I or someone else encounter again.

J.

**Comment by caugner** [comment]
Thank you for your feedback.

I'm glad to hear some of your problems have been resolved and I'm sorry to hear that you're struggling with the current Thunderbird migration.

I can assure you you're not alone and yet it's for the better. After all this, Thunderbird will be prepared for the future and we can expect some great changes once it has been freed from all the legacy stuff. As a major side effect, extensions will be much more safer to use and easier to develop.

As agreed, I'm closing this issue for now.
