### ISSUE TITLE
Compatibility with Thunderbird 64 an onward?

### ISSUE THREAD

**Issue by athelas64** [nostalgy/nostalgy#59]
Would it be possible to make Nostalgy compatible with TB64 (phasing out legacy extensions completely)? Or there is no hope. It seems that with TB64 this versions compatibility nightmare will finally be over, for some time that is...

(https://www.thunderbird.net/en-US/thunderbird/64.0beta/releasenotes/)

Thanks!

**Comment by athelas64** [comment]
I could not find anything more specific than this: 
https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Guides/XUL_Migration_Guide#User_Interface_Components

It seems, given the nature of the add-on, like a nearly complete re-write. Unfortunately, at this moment this is far beyond the scope of my experience, but I am willing to help with vigorous testing and feedback should anybody jump on the occasion.

**Comment by alainfrisch** [comment]
> by using the SDK's low-level APIs you can directly modify the browser chrome.

And this points to https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Low-Level_APIs, but this is already marked as deprecated, in favor of WebExtensions.  Does this apply to Thunderbird?

**Comment by r2evans** [comment]
@alainfrisch, is there a way to fund you to migrate to WebExtensions? (TB68 will be released "soon".)

I'm a big fan of labels-folders (a popular feature in the gmail interface), and this add-on (for me) is a huge part of facilitating it in my day-to-day workflow. Because I'm very keyboard-centric, being able to quickly add several tags to an email is very important to me, and I can find no other way to do it.

I confess to having no WebExtensions experience (nor XUL/XPCOM), though from what I've read I recognize it is not a trivial process for most addons.

**Comment by athelas64** [comment]
@r2evans this is entirely offtopic and I cannot stress enough how Nostalgy improved my days with Thunderbird. In case TB68 will cut Nostalgy off, you might give [Mailspring](https://github.com/Foundry376/Mailspring) a shot. 
(I have left TB because with my email load it became just so slow... Mailspring is snappy, but bugs still appear here and there fairly often).

**Comment by r2evans** [comment]
Thanks, @athelas64. Unfortunately, it does not support adding *any* tags/labels to non-gmail account emails, so it's actually a step back from TB in that regard. Bummer.

**Comment by athelas64** [comment]
@r2evans well I never thought of using labels on non-gmail accounts as they don't natively support it. Let's just hope [https://jmap.io/](url) will take off and it will happen soon :-)

**Comment by r2evans** [comment]
The more email I have, the more logical it seems to allow an email to be in two (or more) folders at once without having to make multiple copies of it; it just "makes sense" to me ... but I am still harboring too much distrust of Google to have them index everything.

... though a significant detractor is that these labels are not typically (or ever) synced to the server, so it's hardly a robust/scalable system. Sigh. Nostalgy allows me to quickly tag an email with "client", "project-within-client", and "side-category" rather quickly and efficiently, then using TB's "Saved Search", I have (well, had) a nice system of saved searches.

Not fully stream-lined, unfortunately.

JMAP looks interesting ... though the prospect of replacing IMAP is ... not good.

**Comment by alainfrisch** [comment]
>  is there a way to fund you to migrate to WebExtensions? 

No, I don't have the time for that.  As far as I'd like Nostalgy to survive (if only for my personal use), my current activities don't allow me to spend more time than a minimum maintainance effort.

**Comment by athelas64** [comment]
Thank you Alain for creating and maintaining this great extension, that for many improves their Thunderbird experience to this day. If somebody will pick up and rewrites your legacy code, great, if they could not, well, I would forever feel warmly nostalgic about Nostalgy.

**Comment by r2evans** [comment]
@alainfrisch, though it is disappointing to see, but I can't blame you for not being able to provide more voluntary time towards this. Thanks for it while it lasted, I hope somebody else can carry the torch.

**Comment by caugner** [comment]
Latest Nostalgy version 0.3 is now compatible with the latest TB version 68.
