### ISSUE TITLE
Ctrl-Left/Right scrolling does not work on summaries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nostalgy/nostalgy#7]
```
When you select multiple messages in the list, Ctrl-Left/Right does not scroll 
the summary view.

This was before the Scroll feature got entirely broken and is now happening 
with the fix of bug#6.

```

Original issue reported on code.google.com by `michael....@gmail.com` on 28 Mar 2012 at 4:10

**Comment by caugner** [comment]
Closing this issue, as <kbd>Ctrl</kbd> + <kbd>Left/Right</kbd> doesn't scroll the summary view, even if Nostalgy is disabled.
