### ISSUE TITLE
V68.4.2 Link Preview not showing

### ISSUE THREAD

**Issue by WebWeaver64** [nostalgy/nostalgy#77]
Hovering over a link doesn't produce a preview of the link at the bottom when Nostalgy is active.
Thanks!

**Comment by opto** [comment]
it does here (win 10 home). Which version? Maybe try the new 1.0.25. Or disable other addons - if the write to the notification area, it might be blocked for nostalgy.

**Comment by WebWeaver64** [comment]
Not sure where to get the 1.0.25 version.  I'm on Windows 10 Home addition. I turned off all other add-ons.

**Comment by WebWeaver64** [comment]
Found it! Yes it is now working. Thanks! :)

**Comment by caugner** [comment]
I can confirm that this is issue does not occur in 0.3 with TB 68.
