### ISSUE TITLE
[Feature Request] double keyboard shortcuts (international support)

### ISSUE THREAD

**Issue by pnevmati** [nostalgy/nostalgy#80]
Us that use two keyboard languages have to switch keyboard back to English/latin to access keyboard shortcuts. If every key function had two shortcut keys then we could program the second language keys as well and avoid the switching.

Perhaps this could be implemented with the "create" key shortcut functionality, but generic functions are not available there, only bound to specific folders.

Hopefully this is simple enough to not consume too many porting resources.

Apparently this was possible for a while using Dorando Keyconfig, but this add-on is not ported to TB68

Many thanks!

**Comment by caugner** [comment]
Just to get a better picture, can you say what other keyboard language you use?

**Comment by pnevmati** [comment]
I use Greek but I guess this would apply for all non-latin-character languages

**Comment by caugner** [comment]
Thank you for bringing this up again.

I'm closing this in favor of #33, which also requests defining two keys per action.
