### ISSUE TITLE
Opening cc: not working properly

### ISSUE THREAD

**Issue by pchestek** [nostalgy/nostalgy#97]
Whenever I type "c" in the body of the email (not with an escape) it opens the cc: box. It means I have to type the body of my email in a separate document (at least any that have a "c" in them) and then cut and paste into my email.

Thunderbird 78.4.1 (64 bit)
Windows 10 Pro ver. 1909, build 18363.1139

Thanks

**Comment by Olifair** [comment]
@pchestek this is not the correct fork of nostalgy for this issue, you should delete this here and post it at : 
https://github.com/opto/nostalgy-xpi/issues

**Comment by pchestek** [comment]
Thanks, sorry for the noise.

Pam
